// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cases: dynamic(() => import("./Cases")),
  homepage_hero: dynamic(() => import("./HomepageHero")),
  team: dynamic(() => import("./Team")),
};
