// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cases: dynamic(() => import("./Cases")),
  cases_hero: dynamic(() => import("./CasesHero")),
  cases_list: dynamic(() => import("./CasesList")),
  homepage_hero: dynamic(() => import("./HomepageHero")),
  services: dynamic(() => import("./Services")),
  team: dynamic(() => import("./Team")),
};
